# Generated by Django 5.2.8 on 2026-03-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employe_name', models.CharField(max_length=50)),
                ('Employe_age', models.CharField(max_length=50)),
                ('Employe_gender', models.CharField(max_length=50)),
                ('Employe_designation', models.CharField(max_length=50)),
                ('Employe_salary', models.CharField(max_length=50)),
                ('Employe_number', models.CharField(max_length=50)),
            ],
        ),
    ]
